;DDS;                  |
;DDS;   ___  ___  ____ | Spectra release: SPECTRA9.9.0
;DDS;   | \ | \ [__  | DDS version: 990.1.6.43701
;DDS;   |__/ |__/ ___] | Target poligon: prod.
;DDS;                  | Timestamp: 2026-09-17 18:32:38.788625 

; ----------------------------------------------------------------------------
; Поток FORTS_PART_REPL - Информация о средствах, лимитах и настройках риск-параметров
[dbscheme:CustReplScheme]
; ----------------------------------------------------------------------------
; Схема CustReplScheme - PART
; Лимиты по клиентам и брокерским фирмам
table=part

[table:CustReplScheme:part]
field=replID,i8
field=replRev,i8
field=replAct,i8
field=client_code,c7
field=money_free,d26.2
field=money_blocked,d26.2
field=vm_reserve,d26.2
field=fee,d26.2
field=limits_set,i1
field=money_old,d26.2
field=money_amount,d26.2
field=money_pledge_amount,d26.2
field=actual_amount_of_base_currency,d26.2
field=is_auto_update_limit,i1
field=moment,t
field=broker_fee,d26.2
field=penalty,d26.2
field=net_option_value,d26.2
field=premium_blocked,d26.2
index=IDX_part_ID_U,UNIQUE,replID
index=IDX_part_REV_U,UNIQUE,replRev
