;DDS;                  |
;DDS;   ___  ___  ____ | Spectra release: SPECTRA9.9.0
;DDS;   | \ | \ [__  | DDS version: 990.1.6.43701
;DDS;   |__/ |__/ ___] | Target poligon: prod.
;DDS;                  | Timestamp: 2026-09-17 18:32:38.278025 

; ----------------------------------------------------------------------------
; Поток FORTS_REFDATA_REPL - Фьючерсы и опционы: справочная и сессионная информация
[dbscheme:CustReplScheme]
; ----------------------------------------------------------------------------
; Схема CustReplScheme - Исходящая схема P2Subfeeder.fo
; Справочник торгуемых инструментов (фьючерсы)
table=fut_sess_contents

[table:CustReplScheme:fut_sess_contents]
field=replID,i8
field=replRev,i8
field=replAct,i8
field=sess_id,i4
field=isin_id,i4
field=short_isin,c25
field=isin,c25
field=name,c75
field=inst_term,i4
field=base_contract_code,c25
field=limit_up,d16.5
field=limit_down,d16.5
field=settlement_price_open,d16.5
field=buy_deposit,d16.2
field=sell_deposit,d16.2
field=roundto,i4
field=min_step,d16.5
field=step_price,d16.5
field=lot_volume,i4
field=last_trade_date,t
field=is_spread,i1
field=d_exp_start,t
field=percent_rate,d6.2
field=settlement_price,d16.5
field=signs,i4
field=ticker,i4
field=state,i4
field=multileg_type,i4
field=legs_qty,i4
field=step_price_clr,d16.5
field=step_price_curr,d16.5
field=pctyield_coeff,d16.5
field=pctyield_total,d16.5
field=d_exp_end,t
field=enforce_ims_half_netting,i1
field=tas_base_fut_isin_id,i4
field=trade_mode_id,i4
field=group_mask,i8
field=d_sess_assign,t
field=trade_period_access,i8
field=buy_deposit_erc,d16.2
field=sell_deposit_erc,d16.2
field=buy_deposit_hrc,d16.2
field=sell_deposit_hrc,d16.2
field=buy_deposit_lrc,d16.2
field=sell_deposit_lrc,d16.2
field=buy_deposit_mrc,d16.2
field=sell_deposit_mrc,d16.2
field=settlement_price_clr,d16.5
index=IDX_fut_sess_contents_ID_U,UNIQUE,replID
index=IDX_fut_sess_contents_REV_U,UNIQUE,replRev
