;DDS;                  |
;DDS;   ___  ___  ____ | Spectra release: SPECTRA9.9.0
;DDS;   | \ | \ [__  | DDS version: 990.1.6.43701
;DDS;   |__/ |__/ ___] | Target poligon: prod.
;DDS;                  | Timestamp: 2026-09-17 18:32:38.752192 

; ----------------------------------------------------------------------------
; Поток FORTS_USERORDERBOOK_REPL - Фьючерсы и Опционы: Cрез стакана приватный
[dbscheme:CustReplScheme]
; ----------------------------------------------------------------------------
; Схема CustReplScheme - 
; Таблица активных фьючерсных и опционных заявок
table=orders

[table:CustReplScheme:orders]
field=replID,i8
field=replRev,i8
field=replAct,i8
field=public_order_id,i8
field=sess_id,i4
field=client_code,c7
field=moment,t
field=moment_ns,u8
field=xstatus,i8
field=xstatus2,i8
field=public_action,i1
field=isin_id,i4
field=dir,i1
field=price,d16.5
field=public_amount,i8
field=public_amount_rest,i8
field=comment,c20
field=ext_id,i4
field=login_from,c20
field=broker_to,c7
field=broker_to_rts,c7
field=date_exp,t
field=id_ord1,i8
field=broker_from_rts,c7
field=aspref,i4
field=private_order_id,i8
field=private_amount,i8
field=private_amount_rest,i8
field=variance_amount,i8
field=disclose_const_amount,i8
field=private_action,i1
field=private_init_moment,t
field=private_init_amount,i8
field=reason,i4
field=match_ref,c10
field=public_init_moment,t
field=public_init_amount,i8
field=compliance_id,c1
field=prevorder_id,i8
index=IDX_orders_ID_U,UNIQUE,replID
index=IDX_orders_REV_U,UNIQUE,replRev
