// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: marketdata.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Tinkoff.InvestApi.V1 {
  /// <summary>
  ///Сервис получения биржевой информации:&lt;/br> **1**. свечи;&lt;/br> **2**. стаканы;&lt;/br> **3**. торговые статусы;&lt;/br> **4**. лента сделок.
  /// </summary>
  public static partial class MarketDataService
  {
    static readonly string __ServiceName = "tinkoff.public.invest.api.contract.v1.MarketDataService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetCandlesRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetCandlesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetCandlesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetCandlesResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetCandlesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetCandlesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetLastPricesRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastPricesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetLastPricesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetLastPricesResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastPricesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetLastPricesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetOrderBookRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetOrderBookRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetOrderBookRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetOrderBookResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetOrderBookResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetOrderBookResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetTradingStatusRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetTradingStatusRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetTradingStatusResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetTradingStatusResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetLastTradesRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastTradesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetLastTradesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetLastTradesResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastTradesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetLastTradesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetClosePricesRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetClosePricesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetClosePricesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetClosePricesResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetClosePricesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetClosePricesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_GetTechAnalysisRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_GetTechAnalysisResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetCandlesRequest, global::Tinkoff.InvestApi.V1.GetCandlesResponse> __Method_GetCandles = new grpc::Method<global::Tinkoff.InvestApi.V1.GetCandlesRequest, global::Tinkoff.InvestApi.V1.GetCandlesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCandles",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetCandlesRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetCandlesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetLastPricesRequest, global::Tinkoff.InvestApi.V1.GetLastPricesResponse> __Method_GetLastPrices = new grpc::Method<global::Tinkoff.InvestApi.V1.GetLastPricesRequest, global::Tinkoff.InvestApi.V1.GetLastPricesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLastPrices",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastPricesRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastPricesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetOrderBookRequest, global::Tinkoff.InvestApi.V1.GetOrderBookResponse> __Method_GetOrderBook = new grpc::Method<global::Tinkoff.InvestApi.V1.GetOrderBookRequest, global::Tinkoff.InvestApi.V1.GetOrderBookResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOrderBook",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetOrderBookRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetOrderBookResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetTradingStatusRequest, global::Tinkoff.InvestApi.V1.GetTradingStatusResponse> __Method_GetTradingStatus = new grpc::Method<global::Tinkoff.InvestApi.V1.GetTradingStatusRequest, global::Tinkoff.InvestApi.V1.GetTradingStatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTradingStatus",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest, global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse> __Method_GetTradingStatuses = new grpc::Method<global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest, global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTradingStatuses",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusesRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetTradingStatusesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetLastTradesRequest, global::Tinkoff.InvestApi.V1.GetLastTradesResponse> __Method_GetLastTrades = new grpc::Method<global::Tinkoff.InvestApi.V1.GetLastTradesRequest, global::Tinkoff.InvestApi.V1.GetLastTradesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLastTrades",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastTradesRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetLastTradesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetClosePricesRequest, global::Tinkoff.InvestApi.V1.GetClosePricesResponse> __Method_GetClosePrices = new grpc::Method<global::Tinkoff.InvestApi.V1.GetClosePricesRequest, global::Tinkoff.InvestApi.V1.GetClosePricesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetClosePrices",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetClosePricesRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetClosePricesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest, global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse> __Method_GetTechAnalysis = new grpc::Method<global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest, global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTechAnalysis",
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetTechAnalysisRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_GetTechAnalysisResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tinkoff.InvestApi.V1.MarketdataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MarketDataService</summary>
    [grpc::BindServiceMethod(typeof(MarketDataService), "BindService")]
    public abstract partial class MarketDataServiceBase
    {
      /// <summary>
      ///Метод запроса исторических свечей по инструменту.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetCandlesResponse> GetCandles(global::Tinkoff.InvestApi.V1.GetCandlesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Метод запроса цен последних сделок по инструментам.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetLastPricesResponse> GetLastPrices(global::Tinkoff.InvestApi.V1.GetLastPricesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Метод получения стакана по инструменту.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetOrderBookResponse> GetOrderBook(global::Tinkoff.InvestApi.V1.GetOrderBookRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetTradingStatusResponse> GetTradingStatus(global::Tinkoff.InvestApi.V1.GetTradingStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse> GetTradingStatuses(global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Метод запроса обезличенных сделок за последний час.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetLastTradesResponse> GetLastTrades(global::Tinkoff.InvestApi.V1.GetLastTradesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Метод запроса цен закрытия торговой сессии по инструментам.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetClosePricesResponse> GetClosePrices(global::Tinkoff.InvestApi.V1.GetClosePricesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse> GetTechAnalysis(global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MarketDataService</summary>
    public partial class MarketDataServiceClient : grpc::ClientBase<MarketDataServiceClient>
    {
      /// <summary>Creates a new client for MarketDataService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MarketDataServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MarketDataService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MarketDataServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MarketDataServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MarketDataServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Метод запроса исторических свечей по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetCandlesResponse GetCandles(global::Tinkoff.InvestApi.V1.GetCandlesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCandles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса исторических свечей по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetCandlesResponse GetCandles(global::Tinkoff.InvestApi.V1.GetCandlesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCandles, null, options, request);
      }
      /// <summary>
      ///Метод запроса исторических свечей по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetCandlesResponse> GetCandlesAsync(global::Tinkoff.InvestApi.V1.GetCandlesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCandlesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса исторических свечей по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetCandlesResponse> GetCandlesAsync(global::Tinkoff.InvestApi.V1.GetCandlesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCandles, null, options, request);
      }
      /// <summary>
      ///Метод запроса цен последних сделок по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetLastPricesResponse GetLastPrices(global::Tinkoff.InvestApi.V1.GetLastPricesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLastPrices(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса цен последних сделок по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetLastPricesResponse GetLastPrices(global::Tinkoff.InvestApi.V1.GetLastPricesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLastPrices, null, options, request);
      }
      /// <summary>
      ///Метод запроса цен последних сделок по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetLastPricesResponse> GetLastPricesAsync(global::Tinkoff.InvestApi.V1.GetLastPricesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLastPricesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса цен последних сделок по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetLastPricesResponse> GetLastPricesAsync(global::Tinkoff.InvestApi.V1.GetLastPricesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLastPrices, null, options, request);
      }
      /// <summary>
      ///Метод получения стакана по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetOrderBookResponse GetOrderBook(global::Tinkoff.InvestApi.V1.GetOrderBookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrderBook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод получения стакана по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetOrderBookResponse GetOrderBook(global::Tinkoff.InvestApi.V1.GetOrderBookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOrderBook, null, options, request);
      }
      /// <summary>
      ///Метод получения стакана по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetOrderBookResponse> GetOrderBookAsync(global::Tinkoff.InvestApi.V1.GetOrderBookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrderBookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод получения стакана по инструменту.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetOrderBookResponse> GetOrderBookAsync(global::Tinkoff.InvestApi.V1.GetOrderBookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOrderBook, null, options, request);
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetTradingStatusResponse GetTradingStatus(global::Tinkoff.InvestApi.V1.GetTradingStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTradingStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetTradingStatusResponse GetTradingStatus(global::Tinkoff.InvestApi.V1.GetTradingStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTradingStatus, null, options, request);
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetTradingStatusResponse> GetTradingStatusAsync(global::Tinkoff.InvestApi.V1.GetTradingStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTradingStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetTradingStatusResponse> GetTradingStatusAsync(global::Tinkoff.InvestApi.V1.GetTradingStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTradingStatus, null, options, request);
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse GetTradingStatuses(global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTradingStatuses(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse GetTradingStatuses(global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTradingStatuses, null, options, request);
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse> GetTradingStatusesAsync(global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTradingStatusesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса статуса торгов по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse> GetTradingStatusesAsync(global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTradingStatuses, null, options, request);
      }
      /// <summary>
      ///Метод запроса обезличенных сделок за последний час.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetLastTradesResponse GetLastTrades(global::Tinkoff.InvestApi.V1.GetLastTradesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLastTrades(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса обезличенных сделок за последний час.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetLastTradesResponse GetLastTrades(global::Tinkoff.InvestApi.V1.GetLastTradesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLastTrades, null, options, request);
      }
      /// <summary>
      ///Метод запроса обезличенных сделок за последний час.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetLastTradesResponse> GetLastTradesAsync(global::Tinkoff.InvestApi.V1.GetLastTradesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLastTradesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса обезличенных сделок за последний час.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetLastTradesResponse> GetLastTradesAsync(global::Tinkoff.InvestApi.V1.GetLastTradesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLastTrades, null, options, request);
      }
      /// <summary>
      ///Метод запроса цен закрытия торговой сессии по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetClosePricesResponse GetClosePrices(global::Tinkoff.InvestApi.V1.GetClosePricesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetClosePrices(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса цен закрытия торговой сессии по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetClosePricesResponse GetClosePrices(global::Tinkoff.InvestApi.V1.GetClosePricesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetClosePrices, null, options, request);
      }
      /// <summary>
      ///Метод запроса цен закрытия торговой сессии по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetClosePricesResponse> GetClosePricesAsync(global::Tinkoff.InvestApi.V1.GetClosePricesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetClosePricesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Метод запроса цен закрытия торговой сессии по инструментам.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetClosePricesResponse> GetClosePricesAsync(global::Tinkoff.InvestApi.V1.GetClosePricesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetClosePrices, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse GetTechAnalysis(global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTechAnalysis(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse GetTechAnalysis(global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTechAnalysis, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse> GetTechAnalysisAsync(global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTechAnalysisAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse> GetTechAnalysisAsync(global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTechAnalysis, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MarketDataServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MarketDataServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MarketDataServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCandles, serviceImpl.GetCandles)
          .AddMethod(__Method_GetLastPrices, serviceImpl.GetLastPrices)
          .AddMethod(__Method_GetOrderBook, serviceImpl.GetOrderBook)
          .AddMethod(__Method_GetTradingStatus, serviceImpl.GetTradingStatus)
          .AddMethod(__Method_GetTradingStatuses, serviceImpl.GetTradingStatuses)
          .AddMethod(__Method_GetLastTrades, serviceImpl.GetLastTrades)
          .AddMethod(__Method_GetClosePrices, serviceImpl.GetClosePrices)
          .AddMethod(__Method_GetTechAnalysis, serviceImpl.GetTechAnalysis).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MarketDataServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCandles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetCandlesRequest, global::Tinkoff.InvestApi.V1.GetCandlesResponse>(serviceImpl.GetCandles));
      serviceBinder.AddMethod(__Method_GetLastPrices, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetLastPricesRequest, global::Tinkoff.InvestApi.V1.GetLastPricesResponse>(serviceImpl.GetLastPrices));
      serviceBinder.AddMethod(__Method_GetOrderBook, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetOrderBookRequest, global::Tinkoff.InvestApi.V1.GetOrderBookResponse>(serviceImpl.GetOrderBook));
      serviceBinder.AddMethod(__Method_GetTradingStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetTradingStatusRequest, global::Tinkoff.InvestApi.V1.GetTradingStatusResponse>(serviceImpl.GetTradingStatus));
      serviceBinder.AddMethod(__Method_GetTradingStatuses, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetTradingStatusesRequest, global::Tinkoff.InvestApi.V1.GetTradingStatusesResponse>(serviceImpl.GetTradingStatuses));
      serviceBinder.AddMethod(__Method_GetLastTrades, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetLastTradesRequest, global::Tinkoff.InvestApi.V1.GetLastTradesResponse>(serviceImpl.GetLastTrades));
      serviceBinder.AddMethod(__Method_GetClosePrices, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetClosePricesRequest, global::Tinkoff.InvestApi.V1.GetClosePricesResponse>(serviceImpl.GetClosePrices));
      serviceBinder.AddMethod(__Method_GetTechAnalysis, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.InvestApi.V1.GetTechAnalysisRequest, global::Tinkoff.InvestApi.V1.GetTechAnalysisResponse>(serviceImpl.GetTechAnalysis));
    }

  }
  public static partial class MarketDataStreamService
  {
    static readonly string __ServiceName = "tinkoff.public.invest.api.contract.v1.MarketDataStreamService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.MarketDataRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.MarketDataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.MarketDataResponse> __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.MarketDataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest> __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataServerSideStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.MarketDataRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse> __Method_MarketDataStream = new grpc::Method<global::Tinkoff.InvestApi.V1.MarketDataRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "MarketDataStream",
        __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse> __Method_MarketDataServerSideStream = new grpc::Method<global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "MarketDataServerSideStream",
        __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataServerSideStreamRequest,
        __Marshaller_tinkoff_public_invest_api_contract_v1_MarketDataResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tinkoff.InvestApi.V1.MarketdataReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of MarketDataStreamService</summary>
    [grpc::BindServiceMethod(typeof(MarketDataStreamService), "BindService")]
    public abstract partial class MarketDataStreamServiceBase
    {
      /// <summary>
      ///Bi-directional стрим предоставления биржевой информации.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task MarketDataStream(grpc::IAsyncStreamReader<global::Tinkoff.InvestApi.V1.MarketDataRequest> requestStream, grpc::IServerStreamWriter<global::Tinkoff.InvestApi.V1.MarketDataResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Server-side стрим предоставления биржевой информации.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task MarketDataServerSideStream(global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest request, grpc::IServerStreamWriter<global::Tinkoff.InvestApi.V1.MarketDataResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MarketDataStreamService</summary>
    public partial class MarketDataStreamServiceClient : grpc::ClientBase<MarketDataStreamServiceClient>
    {
      /// <summary>Creates a new client for MarketDataStreamService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MarketDataStreamServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MarketDataStreamService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MarketDataStreamServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MarketDataStreamServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MarketDataStreamServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Bi-directional стрим предоставления биржевой информации.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Tinkoff.InvestApi.V1.MarketDataRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse> MarketDataStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MarketDataStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Bi-directional стрим предоставления биржевой информации.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Tinkoff.InvestApi.V1.MarketDataRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse> MarketDataStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_MarketDataStream, null, options);
      }
      /// <summary>
      ///Server-side стрим предоставления биржевой информации.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Tinkoff.InvestApi.V1.MarketDataResponse> MarketDataServerSideStream(global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MarketDataServerSideStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Server-side стрим предоставления биржевой информации.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Tinkoff.InvestApi.V1.MarketDataResponse> MarketDataServerSideStream(global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_MarketDataServerSideStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MarketDataStreamServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MarketDataStreamServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MarketDataStreamServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_MarketDataStream, serviceImpl.MarketDataStream)
          .AddMethod(__Method_MarketDataServerSideStream, serviceImpl.MarketDataServerSideStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MarketDataStreamServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_MarketDataStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Tinkoff.InvestApi.V1.MarketDataRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse>(serviceImpl.MarketDataStream));
      serviceBinder.AddMethod(__Method_MarketDataServerSideStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Tinkoff.InvestApi.V1.MarketDataServerSideStreamRequest, global::Tinkoff.InvestApi.V1.MarketDataResponse>(serviceImpl.MarketDataServerSideStream));
    }

  }
}
#endregion
