using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OsEngine.Market.Servers.Lmax
{
    /// <summary>
	/// field tags for FIX protocol
    /// теги полей, используемые FIX протоколом
    /// </summary>
    public enum Tags
    {
        Account = 1,
        AvgPx = 6,
        BeginSeqNo = 7,
        BeginString = 8,
        BodyLength = 9,
        CheckSum = 10,
        ClOrdID = 11,
        CumQty = 14,
        EndSeqNo = 16,
        ExecID = 17,
        ExecInst = 18,
        SecurityIDSource = 22,
        LastPx = 31,
        LastQty = 32,
        MsgSeqNum = 34,
        MsgType = 35,
        NewSeqNo = 36,
        OrderID = 37,
        OrderQty = 38,
        OrdStatus = 39,
        OrdType = 40,
        OrigClOrdID = 41,
        PossDupFlag = 43,
        Price = 44,
        RefSeqNum = 45,
        SecurityID = 48,
        SenderCompID = 49,
        SendingTime = 52,
        Side = 54,
        Symbol = 55,
        TargetCompID = 56,
        Text = 58,
        TimeInForce = 59,
        TransactTime = 60,
        SettlDate = 64,
        TradeDate = 75,
        Signature = 89,
        SignatureLength = 93,
        RawDataLength = 95,
        RawData = 96,
        PossResend = 97,
        EncryptMethod = 98,
        StopPx = 99,
        ExDestination = 100,
        CxlRejReason = 102,
        OrdRejReason = 103,
        HeartBtInt = 108,
        TestReqID = 112,
        OrigSendingTime = 122,
        GapFillFlag = 123,
        ResetSeqNumFlag = 141,
        NoRelatedSym = 146,
        ExecType = 150,
        LeavesQty = 151,
        MDReqID = 262,
        SubscriptionRequestType = 263,
        MarketDepth = 264,
        MDUpdateType = 265,
        AggregatedBook = 266,
        NoMDEntryTypes = 267,
        NoMDEntries = 268,
        MDEntryType = 269,
        MDEntryPx = 270,
        MDEntrySize = 271,
        MDEntryDate = 272,
        MDEntryTime = 273,
        MDReqRejReason = 281,
        EncodedTextLen = 354,
        EncodedText = 355,
        RefTagID = 371,
        RefMsgType = 372,
        SessionRejectReason = 373,
        MaxMessageSize = 383,
        NoMsgTypes = 384,
        MsgDirection = 385,
        CxlRejResponseTo = 434,
        TestMessageIndicator = 464,
        SecondaryExecID = 527,
        NoSides = 552,
        Username = 553,
        Password = 554,
        TradeRequestID = 568,
        TradeRequestType = 569,
        NoDates = 580,
        TotNumTradeReports = 748,
        TradeRequestResult = 749,
        TradeRequestStatus = 750,
        NextExpectedMsgSeqNum = 789,
        OrdStatusReqID = 790,
        LastRptRequested = 912,
        MatchIncrement = 1089,
    }
}
